### ISSUE TITLE
license ambiguity

### ISSUE THREAD

**Issue by pghmcfc** [briandfoy/module-extract-use#3]
The newly-included 'LICENSE' file says that the module is licensed "under the same terms as perl
itself, under the Artistic License 2.0", which is self-contradicting because perl is licensed under either GPL or Artistic 1 licenses, not Artistic 2. The text in the module files themselves say "same as perl", without mentioning Artistic 2.0. I suspect you mean to license the module as Artistic 2.0, in which case it would be better to get rid of the "same as perl" text everywhere and just say "Artistic 2.0" instead.

Incidentally, it would help downstream packagers if you could be consistent about how many digits after the decimal point you use in your version numbers, as downstream package managers such as rpm tend to use semantic versioning, for which 1.042 would be "higher" than 1.05 for instance.

**Comment by briandfoy** [comment]
License issue is fixed. It's Artistic 2.0.

I don't think there's an issue with the version number here. 1.042 should be the highest at this point (with 1.043 on the way). There's never been a 1.05 version. Perl tools use implicit three digit numbering and I'm correcting my versions to make that explicit.

Thanks,

**Comment by pghmcfc** [comment]
The 1.05 was a hypothetical future version: 1.05 would be bad from a downstream versioning point of view, but 1.050 would be fine. So if you're sticking with three digit numbering from this point onwards there should be no problem.
